CREATE USER admin WITH PASSWORD 'reallyadmin' CREATEDB;

CREATE DATABASE todo;


\c todo

CREATE TABLE IF NOT EXISTS test_table (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

GRANT ALL PRIVILEGES ON DATABASE todo TO admin;

GRANT ALL PRIVILEGES ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;

ALTER TABLE test_table OWNER TO admin;

ALTER USER admin CREATEDB;